dwo_config_prototype:

  prototypes:

    feature:
      configuration_class: 'Dwo\FlaggingBundle\DependencyInjection\Configuration'
      prototype_path: 'dwo_flagging.features'
      manager: 'dwo_flagging_manager.manager.config_prototype'