list:
    path:     /
    defaults: { _controller: Dwo\FlaggingManagerBundle\Controller\FeatureController::listAction }
    methods:  [GET]

read:
    path:     /{featureName}
    defaults: { _controller: Dwo\FlaggingManagerBundle\Controller\FeatureController::readAction }
    methods:  [GET]

write:
    path:     /{featureName}
    defaults: { _controller: Dwo\FlaggingManagerBundle\Controller\FeatureController::writeAction }
    methods:  [POST]