flagging_manager_list:
    path:     /
    defaults: { _controller: Dwo\FlaggingManagerBundle\Controller\FeatureController::listAction }
    methods:  [GET]

flagging_manager_read:
    path:     /{featureName}
    defaults: { _controller: Dwo\FlaggingManagerBundle\Controller\FeatureController::readAction }
    methods:  [GET]

flagging_manager_write:
    path:     /{featureName}
    defaults: { _controller: Dwo\FlaggingManagerBundle\Controller\FeatureController::writeAction }
    methods:  [POST]